mean: [123.675, 116.28, 103.53] # just using IN norms here
std: [58.395, 57.12, 57.375] # just using IN norms here
num_classes: 2
arch: 'resnet18'
arch_type: 'resnet'

batch_size: 512
num_workers: 1
imgsz: 75

train_beton: 'celeba_age/celeba_age_train.beton'
test_beton: 'celeba_age/celeba_age_test.beton'
val_beton: 'celeba_age/celeba_age_val.beton'

train_img_decoder: center_crop_full
val_img_decoder: center_crop_full

shuffle: True
drop_last: True

train_aug: imagenet_train_aug

training:
    epochs: 30
    lr: 0.02
    optimizer:
        momentum: 0.9
        weight_decay: 5.0E-4
    lr_scheduler:
        type: cyclic
        lr_peak_epoch: 2
    